type1:
  inputFile: input/t1.txt
  defineFile: input/define.txt
  entityFile: 
    - 手袋(Ｌ０１)=input/TestTable1BaseEntity.java
    - Ｌ０２(L00)KKK=input/TestTable2BaseEntity.java
    - Ｌ０３(L11)TTT=input/TestTable3BaseEntity.java
  entityInstance:
    - 手袋(Ｌ０１)=testTable1
    - Ｌ０２(L00)KKK=test222
    - Ｌ０３(L11)TTT=testTable333
  outputFile: output/GeneratedCode.java
type2:
  inputFile: input/t2.txt
  defineFile: input/define.txt
  entityFile: 
    - 手袋(Ｌ０１)=input/TestTable1BaseEntity.java
    - Ｌ０２(L00)KKK=input/TestTable2BaseEntity.java
    - Ｌ０３(L11)TTT=input/TestTable3BaseEntity.java
  entityInstance:
    - 手袋(Ｌ０１)=testTable1
    - Ｌ０２(L00)KKK=test222
    - Ｌ０３(L11)TTT=testTable333
  outputFile: output/GeneratedCode2.java
  logicOperatorMapping:
    "=\"\"": "StrUtil.isEmpty"
    "!=\"\"": "!StrUtil.isEmpty"
    "=str": "StrUtil.eq"
    "!=str": "!StrUtil.eq"
    "=num": "NumUtil.eq"
    "!=num": "!NumUtil.eq"
    ">=": "NumUtil.ge"
    "<=num": "NumUtil.le"
    ">num": "NumUtil.gt"
    "<num": "NumUtil.lt"
  enableLogicConversion: true
type3:
  inputFile: input/arrays.xlsx
type4:
  inputFile: input/variables.xlsx
